language: cpp
sudo: required
compiler:
    - gcc
install:
    - sudo apt-get -y update
    - sudo apt-get -y install build-essential libgl1-mesa-dev
    - sudo apt-get -y upgrade cmake
script:
    - cmake .
    - make check
