language: cpp
sudo: required
compiler:
    - gcc
install:
    - sudo apt-get -y update
    - sudo apt-get -y install build-essential libgl1-mesa-dev
    - git clone https://chromium.googlesource.com/external/gyp build/gyp
script:
    - ./grapl_gyp.py
    - cd out && make
